image: europe-docker.pkg.dev/gitpod-artifacts/docker-dev/workspace-dotnet-vnc:2022-02-28-07-30-13
vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - EditorConfig.EditorConfig
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - vscjava.vscode-java-pack
    - fwcd.kotlin
