image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:cw-bmp-leeway.0
workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
tasks:
  - name: Go
    init: leeway exec --filter-type go -v -- go mod verify
    openMode: split-right
vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - EditorConfig.EditorConfig
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - vscjava.vscode-java-pack
    - fwcd.kotlin
